version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast_api_web
    networks:
      - my-network  
    ports:
      - "8090:8000" # 使用应用配置的端口
    volumes:
      - .:/app
      - ./logs:/app/logs # 日志持久化
    env_file:
      - .env # 使用默认的环境配置文件
    restart: unless-stopped
    command: python main.py

networks:
  my-network:
    external: true

  # celery_worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #     - ./logs:/app/logs # 日志持久化
  #   env_file:
  #     - .env # 使用默认的环境配置文件
  #   restart: unless-stopped
  #   command: celery -A app.core.celery_app worker --loglevel=info
  #   depends_on:
  #     - web

  # celery_beat:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #     - ./logs:/app/logs # 日志持久化
  #   env_file:
  #     - .env # 使用默认的环境配置文件
  #   restart: unless-stopped
  #   command: celery -A app.core.celery_app beat --loglevel=info
  #   depends_on:
  #     - web
  #     - celery_worker
