"""Initial tables

Revision ID: 0be8794bddcd
Revises: 
Create Date: 2025-05-02 14:40:34.319206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be8794bddcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_index('idx_email', table_name='users')
    op.drop_index('idx_username', table_name='users')
    op.drop_index('username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('username', 'users', ['username'], unique=False)
    op.create_index('idx_username', 'users', ['username'], unique=False)
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.create_index('email', 'users', ['email'], unique=False)
    # ### end Alembic commands ### 
